# Generated by Django 3.2.4 on 2021-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0002_auto_20210628_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_1',
            field=models.CharField(max_length=264, null=True, verbose_name='Your Full Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=264, null=True, verbose_name='Your Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Your Personal Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
    ]
