# Generated by Django 3.2.4 on 2021-06-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPayment', '0002_auto_20210627_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='adress',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(max_length=40, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Area Zip Code'),
        ),
    ]
