# Generated by Django 3.2.4 on 2021-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPayment', '0004_rename_adress_billingaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Shipping Address'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Area Post Code'),
        ),
    ]
