# Generated by Django 3.2.4 on 2021-06-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, verbose_name='Category title')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Products', verbose_name='Product Image')),
                ('name', models.CharField(max_length=264, verbose_name='Product Name')),
                ('description', models.TextField(max_length=2000, verbose_name='Prdouct Description')),
                ('preview_text', models.CharField(max_length=400, verbose_name='Short Description')),
                ('regular_price', models.FloatField(verbose_name='Regular Price')),
                ('discounted_price', models.FloatField(verbose_name='Discounted Price')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='AppShop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
